
// This file has been generated by the GUI designer. Do not modify.
namespace CyrusBuilt.MonoPluginFramework.UI
{
	public partial class FormChangeValue
	{
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Entry entrySetting;
		private global::Gtk.Label labelSetting;
		private global::Gtk.Entry entryType;
		private global::Gtk.Label labelType;
		private global::Gtk.Entry entryValue;
		private global::Gtk.Label labelValue;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CyrusBuilt.MonoPluginFramework.UI.FormChangeValue
			this.WidthRequest = 344;
			this.HeightRequest = 167;
			this.Name = "CyrusBuilt.MonoPluginFramework.UI.FormChangeValue";
			this.Title = global::Mono.Unix.Catalog.GetString ("Edit Setting");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Dialog);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 344;
			this.DefaultHeight = 167;
			// Internal child CyrusBuilt.MonoPluginFramework.UI.FormChangeValue.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.HeightRequest = 220;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entrySetting = new global::Gtk.Entry ();
			this.entrySetting.WidthRequest = 280;
			this.entrySetting.CanFocus = true;
			this.entrySetting.Name = "entrySetting";
			this.entrySetting.IsEditable = false;
			this.entrySetting.InvisibleChar = '●';
			this.fixed2.Add (this.entrySetting);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entrySetting]));
			w2.X = 74;
			w2.Y = 39;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.labelSetting = new global::Gtk.Label ();
			this.labelSetting.Name = "labelSetting";
			this.labelSetting.LabelProp = global::Mono.Unix.Catalog.GetString ("Setting:");
			this.fixed2.Add (this.labelSetting);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.labelSetting]));
			w3.X = 12;
			w3.Y = 42;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entryType = new global::Gtk.Entry ();
			this.entryType.WidthRequest = 280;
			this.entryType.CanFocus = true;
			this.entryType.Name = "entryType";
			this.entryType.IsEditable = false;
			this.entryType.InvisibleChar = '●';
			this.fixed2.Add (this.entryType);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entryType]));
			w4.X = 74;
			w4.Y = 83;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.labelType = new global::Gtk.Label ();
			this.labelType.Name = "labelType";
			this.labelType.LabelProp = global::Mono.Unix.Catalog.GetString ("Type:");
			this.fixed2.Add (this.labelType);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.labelType]));
			w5.X = 12;
			w5.Y = 85;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entryValue = new global::Gtk.Entry ();
			this.entryValue.WidthRequest = 280;
			this.entryValue.CanFocus = true;
			this.entryValue.Name = "entryValue";
			this.entryValue.IsEditable = true;
			this.entryValue.InvisibleChar = '●';
			this.fixed2.Add (this.entryValue);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entryValue]));
			w6.X = 75;
			w6.Y = 126;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.labelValue = new global::Gtk.Label ();
			this.labelValue.Name = "labelValue";
			this.labelValue.LabelProp = global::Mono.Unix.Catalog.GetString ("Value:");
			this.fixed2.Add (this.labelValue);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.labelValue]));
			w7.X = 12;
			w7.Y = 128;
			w1.Add (this.fixed2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Internal child CyrusBuilt.MonoPluginFramework.UI.FormChangeValue.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonCancel]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonOk]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.Realized += new global::System.EventHandler (this.OnRealized);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
