
// This file has been generated by the GUI designer. Do not modify.
namespace CyrusBuilt.MonoPluginFramework.UI
{
	public partial class FormSettingsDialog
	{
		private global::Gtk.Fixed fixedMain;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeviewPlugins;
		private global::Gtk.Button buttonClose;
		private global::Gtk.Button buttonSave;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CyrusBuilt.MonoPluginFramework.UI.FormSettingsDialog
			this.WidthRequest = 540;
			this.HeightRequest = 387;
			this.Name = "CyrusBuilt.MonoPluginFramework.UI.FormSettingsDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Plugin Settings");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("CyrusBuilt.MonoPluginFramework.plugin_link.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.DefaultWidth = 540;
			this.DefaultHeight = 387;
			this.DestroyWithParent = true;
			// Container child CyrusBuilt.MonoPluginFramework.UI.FormSettingsDialog.Gtk.Container+ContainerChild
			this.fixedMain = new global::Gtk.Fixed ();
			this.fixedMain.Name = "fixedMain";
			this.fixedMain.HasWindow = false;
			// Container child fixedMain.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeviewPlugins = new global::Gtk.TreeView ();
			this.treeviewPlugins.WidthRequest = 495;
			this.treeviewPlugins.HeightRequest = 285;
			this.treeviewPlugins.CanFocus = true;
			this.treeviewPlugins.Name = "treeviewPlugins";
			this.GtkScrolledWindow.Add (this.treeviewPlugins);
			this.fixedMain.Add (this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixedMain [this.GtkScrolledWindow]));
			w2.X = 4;
			w2.Y = 3;
			// Container child fixedMain.Gtk.Fixed+FixedChild
			this.buttonClose = new global::Gtk.Button ();
			this.buttonClose.WidthRequest = 75;
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = global::Mono.Unix.Catalog.GetString ("Close");
			this.fixedMain.Add (this.buttonClose);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixedMain [this.buttonClose]));
			w3.X = 443;
			w3.Y = 317;
			// Container child fixedMain.Gtk.Fixed+FixedChild
			this.buttonSave = new global::Gtk.Button ();
			this.buttonSave.WidthRequest = 75;
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString ("Save");
			this.fixedMain.Add (this.buttonSave);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixedMain [this.buttonSave]));
			w4.X = 362;
			w4.Y = 317;
			this.Add (this.fixedMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.Realized += new global::System.EventHandler (this.OnRealized);
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.buttonClose.Clicked += new global::System.EventHandler (this.OnButtonCloseClicked);
			this.buttonSave.Clicked += new global::System.EventHandler (this.OnButtonSaveClicked);
		}
	}
}
